"""Initial migration

Revision ID: 7abd32ed259e
Revises: 
Create Date: 2024-07-12 11:29:46.056211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abd32ed259e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_title', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('note_status', sa.String(length=80), nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('note_status')
        batch_op.drop_column('app_title')

    # ### end Alembic commands ###
